# Generated by Django 2.2.7 on 2019-12-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0002_auto_20191204_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'default_permissions': ('add', 'detail', 'list', 'change', 'delete', 'enable', 'disable', 'export', 'import', 'alert', 'error', 'admin_perm', 'askfor_perm'), 'ordering': ['country'], 'verbose_name': 'Nationalité', 'verbose_name_plural': 'Nationalités'},
        ),
    ]
