# Generated by Django 2.2.7 on 2019-12-12 17:11

from django.db import migrations, models
import mighty.functions
import mighty.models


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0003_auto_20191204_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='to_search',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Champs dédié à la recherche'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='to_search',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Champs dédié à la recherche'),
        ),
        migrations.AlterField(
            model_name='template',
            name='to_search',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Champs dédié à la recherche'),
        ),
        migrations.AlterField(
            model_name='user',
            name='codes',
            field=mighty.models.JSONField(blank=True, null=True, verbose_name='Codes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default=mighty.functions.key, max_length=32, unique=True, verbose_name='Clé'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign',
            field=models.CharField(default=mighty.functions.key, max_length=32, unique=True, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='user',
            name='to_search',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Champs dédié à la recherche'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokens',
            field=mighty.models.JSONField(blank=True, null=True, verbose_name='Jetons'),
        ),
    ]
