from django.utils.translation import gettext_lazy as _

f_Bar = _("Bar")
f_Bipolar = _("Bipolar")
f_Funnel = _("Funnel")
f_Gauge = _("Gauge")
f_HorizontalBar = _("Horizontal Bar")
f_HorizontalProgressbars = _("Horizontal Progress bars")
f_Line = _("Line")
f_Pie = _("Pie")
f_Radar = _("Radar")
f_Rose = _("Rose")
f_Scatter = _("Scatter")
f_SemicircularProgressbars = _("Semi-circular Progress bars")
f_VerticalProgressbars = _("Vertical Progress bars")
f_Waterfall = _("Waterfall")
f_Donut = _("Donut")
f_Fuel = _("Fuel")
f_Funnel = _("Funnel")
f_Gantt = _("Gantt")
f_Meter = _("Meter")
f_Odometer = _("Odometer")
f_Radialscatter = _("Radial scatter")
f_Thermometer = _("Thermometer")