template = (
    'name',
    'graphtype',
    'lg_width',
    'lg_height',
    'lg_max_width',
    'lg_title_size',
    'lg_text_size',
    'md_width',
    'md_height',
    'md_max_width',
    'md_title_size',
    'md_text_size',
    'sm_width',
    'sm_height',
    'sm_max_width',
    'sm_title_size',
    'sm_text_size',
    'options',
    'responsive_options',
)

graph = (
    'title', 
    'is_responsive', 
    'templates', 
    'values', 
    'container', 
    'options', 
    'responsive_options',
    'width',
    'height',
    'max_width',
    'title_size',
    'text_size',
)