# Generated by Django 2.2.5 on 2019-10-24 16:46

from django.db import migrations, models
import mighty.functions
import mighty.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Mis à jour par')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, default='none.jpg', null=True, upload_to=mighty.functions.image_directory_path)),
                ('display', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom par défaut de l'objet")),
                ('to_search', models.TextField(blank=True, db_index=True, editable=False, null=True, verbose_name='Champs dédié à la recherche')),
                ('signhash', models.CharField(blank=True, db_index=True, editable=False, max_length=254, null=True, unique=True, verbose_name='Hash Signature')),
                ('is_disable', models.BooleanField(default=False, editable=False, verbose_name='Objet désactivé')),
                ('alerts', mighty.models.JSONField(blank=True, null=True, verbose_name='Alertes')),
                ('errors', mighty.models.JSONField(blank=True, null=True, verbose_name='Erreurs')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('Bar', models.BooleanField(default=False, verbose_name='Bar')),
                ('Bipolar', models.BooleanField(default=False, verbose_name='Bipolar')),
                ('Gauge', models.BooleanField(default=False, verbose_name='Gauge')),
                ('HorizontalBar', models.BooleanField(default=False, verbose_name='Horizontal Bar')),
                ('HorizontalProgressbars', models.BooleanField(default=False, verbose_name='Horizontal Progress bars')),
                ('Line', models.BooleanField(default=False, verbose_name='Line')),
                ('Pie', models.BooleanField(default=False, verbose_name='Pie')),
                ('Radar', models.BooleanField(default=False, verbose_name='Radar')),
                ('Rose', models.BooleanField(default=False, verbose_name='Rose')),
                ('Scatter', models.BooleanField(default=False, verbose_name='Scatter')),
                ('SemicircularProgressbars', models.BooleanField(default=False, verbose_name='Semi-circular Progress bars')),
                ('VerticalProgressbars', models.BooleanField(default=False, verbose_name='Vertical Progress bars')),
                ('Waterfall', models.BooleanField(default=False, verbose_name='Waterfall')),
                ('Donut', models.BooleanField(default=False, verbose_name='Donut')),
                ('Fuel', models.BooleanField(default=False, verbose_name='Fuel')),
                ('Funnel', models.BooleanField(default=False, verbose_name='Funnel')),
                ('Gantt', models.BooleanField(default=False, verbose_name='Gantt')),
                ('Meter', models.BooleanField(default=False, verbose_name='Meter')),
                ('Odometer', models.BooleanField(default=False, verbose_name='Odometer')),
                ('Radialscatter', models.BooleanField(default=False, verbose_name='Radial scatter')),
                ('Thermometer', models.BooleanField(default=False, verbose_name='Thermometer')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'detail', 'list', 'change', 'delete', 'enable', 'disable', 'admin_perm', 'askfor_perm'),
            },
        ),
    ]
