# Generated by Django 2.2.5 on 2019-10-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
