# Generated by Django 2.2.5 on 2019-10-25 13:25

from django.db import migrations, models
import mighty.functions
import mighty.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grapher', '0002_delete_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Mis à jour par')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, default='none.jpg', null=True, upload_to=mighty.functions.image_directory_path)),
                ('display', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom par défaut de l'objet")),
                ('to_search', models.TextField(blank=True, db_index=True, editable=False, null=True, verbose_name='Champs dédié à la recherche')),
                ('signhash', models.CharField(blank=True, db_index=True, editable=False, max_length=254, null=True, unique=True, verbose_name='Hash Signature')),
                ('is_disable', models.BooleanField(default=False, editable=False, verbose_name='Objet désactivé')),
                ('alerts', mighty.models.JSONField(blank=True, null=True, verbose_name='Alertes')),
                ('errors', mighty.models.JSONField(blank=True, null=True, verbose_name='Erreurs')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('graphtype', models.CharField(choices=[('BAR', 'Bar'), ('BIPOLAR', 'Bipolar'), ('FUNNEL', 'Funnel'), ('GAUGE', 'Gauge'), ('HORIZONTALBAR', 'Horizontal Bar'), ('HORIZONTALPROGRESSBARS', 'Horizontal Progress bars'), ('LINE', 'Line'), ('PIE', 'Pie'), ('RADAR', 'Radar'), ('ROSE', 'Rose'), ('SCATTER', 'Scatter'), ('SEMICIRCULARPROGRESSBA', 'Semi-circular Progress bars'), ('VERTICALPROGRESSBARS', 'Vertical Progress bars'), ('WATERFALL', 'Waterfall'), ('DONUT', 'Donut'), ('GANTT', 'Gantt'), ('METER', 'Meter'), ('ODOMETER', 'Odometer'), ('RADIALSCATTER', 'Radial scatter'), ('THERMOMETER', 'Thermometer')], default='BAR', max_length=100, verbose_name='Type')),
                ('is_responsive', models.BooleanField(default=False, verbose_name='responsive')),
                ('lg_width', models.PositiveSmallIntegerField(default=800, verbose_name='Large width')),
                ('lg_height', models.PositiveSmallIntegerField(default=400, verbose_name='Large height')),
                ('lg_max_width', models.PositiveSmallIntegerField(default=1200, verbose_name='Large max witdh')),
                ('lg_title_size', models.PositiveSmallIntegerField(default=18, verbose_name='Large title size')),
                ('lg_text_size', models.PositiveSmallIntegerField(default=14, verbose_name='Large text size')),
                ('md_width', models.PositiveSmallIntegerField(default=600, verbose_name='Medium width')),
                ('md_height', models.PositiveSmallIntegerField(default=300, verbose_name='Medium height')),
                ('md_max_width', models.PositiveSmallIntegerField(default=992, verbose_name='Medium max witdh')),
                ('md_title_size', models.PositiveSmallIntegerField(default=14, verbose_name='Medium title size')),
                ('md_text_size', models.PositiveSmallIntegerField(default=12, verbose_name='Medium text size')),
                ('sm_width', models.PositiveSmallIntegerField(default=400, verbose_name='Small width')),
                ('sm_height', models.PositiveSmallIntegerField(default=200, verbose_name='Small height')),
                ('sm_max_width', models.PositiveSmallIntegerField(default=768, verbose_name='Small max witdh')),
                ('sm_title_size', models.PositiveSmallIntegerField(default=12, verbose_name='Small title size')),
                ('sm_text_size', models.PositiveSmallIntegerField(default=10, verbose_name='Small text size')),
                ('options', mighty.models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'detail', 'list', 'change', 'delete', 'enable', 'disable', 'admin_perm', 'askfor_perm'),
            },
        ),
    ]
