# Generated by Django 2.2.5 on 2019-10-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0003_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
